name: msal_flutter
description: A Microsoft Authentication Library wrapper for Android and iOS
version: 2.0.0-alpha.1
homepage: https://github.com/moodio/msal-flutter
repository: https://github.com/moodio/msal-flutter
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: uk.co.moodio.msal_flutter
        pluginClass: MsalFlutterPlugin
      ios:
        pluginClass: MsalFlutterPlugin